version: '2'
services:
    abcde-app:
        image: abcde
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://abcde-mysql:3306/abcde?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    abcde-mysql:
        extends:
            file: mysql.yml
            service: abcde-mysql
